python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path /gemini/space/yifq/zhaozy/zhangda/code/One-fits-all/MSL \
  --model_id MSL \
  --model FusAD \
  --data MSL \
  --features M \
  --seq_len 100 \
  --enc_in 55 \
  --c_out 55 \
  --d_model 256 \
  --e_layers 3 \
  --dropout 0.1 \
  --patch_size 8 \
  --stride 4 \
  --anomaly_ratio 1 \
  --batch_size 128 \
  --learning_rate 0.0001 \
  --train_epochs 1
