python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path ./data/SMD \
  --model_id SMD \
  --model FusAD \
  --data SMD \
  --features M \
  --seq_len 100 \
  --enc_in 38 \
  --c_out 38 \
  --d_model 256 \
  --e_layers 3 \
  --dropout 0.1 \
  --patch_size 8 \
  --stride 4 \
  --anomaly_ratio 0.5 \
  --batch_size 128 \
  --learning_rate 0.0001 \
  --train_epochs 10
